"""
Stamper - Creates capsule folders from source material.
"""

import json
import shutil
from pathlib import Path
from datetime import datetime
from aether import generate_id, get_required_files, REQUIRED_SUFFIXES

DEFAULT_DEFINITION = {
    "pipeline": {"distill": {"enabled": True}, "augment": {"enabled": True},
                 "generate": {"enabled": True}, "review": {"enabled": True}},
    "review": {"min_length": 10, "max_length": 10000, "threshold": 0.8},
}
DEFAULT_PERSONA = {"tone": "neutral", "style": "informative", "constraints": []}
DEFAULT_KB = "# Knowledge Base\n\n<!-- Add knowledge content here -->\n"
DEFAULT_KG = {
    "@context": {"rdfs": "http://www.w3.org/2000/01/rdf-schema#", "aether": "http://aether.dev/ontology#"},
    "@graph": [],
}

# PSI projection graph default structure (optional 6th file)
DEFAULT_PSI = {
    "@context": {
        "aether": "http://aether.dev/ontology#",
        "psi": "http://aether.dev/projection#"
    },
    "@type": "psi:ProjectionGraph",
    "psi:capsule": "",  # Will be set to capsule-id
    "psi:version": "1.0.0",
    "psi:projections": []
}

# PSI projection limits
PSI_PROJECTION_WARN_LIMIT = 80
PSI_PROJECTION_MAX_LIMIT = 100

# Optional capsule sidecar files (included when present, never required)
OPTIONAL_CAPSULE_FILES = ["engram.jsonld"]


def _parse_claude_md(content: str) -> dict:
    """
    Parse a CLAUDE.md file and return structured data for capsule creation.

    Returns dict with: name, persona, kb_sections, kg_nodes, is_aether_export
    """
    import re

    result = {
        "name": None,
        "persona": {"tone": "neutral", "style": "informative", "constraints": []},
        "kb_sections": [],
        "kg_nodes": [],
        "is_aether_export": False,
    }

    # Step 1: Detect AETHER export marker
    result["is_aether_export"] = "Generated by AETHER Export" in content

    # Step 2: Extract name from first # heading
    lines = content.split("\n")
    for line in lines:
        if line.startswith("# ") and not line.startswith("## "):
            result["name"] = line[2:].strip()
            break

    # Step 3: Split into sections by ## headers
    sections = []
    current_header = None
    current_body = []

    for line in lines:
        if line.startswith("## "):
            # Save previous section
            if current_header is not None:
                sections.append((current_header, "\n".join(current_body).strip()))
            current_header = line[3:].strip()
            current_body = []
        elif current_header is not None:
            current_body.append(line)

    # Save last section
    if current_header is not None:
        sections.append((current_header, "\n".join(current_body).strip()))

    # Step 4: Map sections to output
    for header, body in sections:
        header_lower = header.lower()

        # Identity / Persona section -> extract tone, style
        if header_lower in ("identity", "persona"):
            for line in body.split("\n"):
                line = line.strip()
                if line.startswith("- Tone:"):
                    result["persona"]["tone"] = line[7:].strip()
                elif line.startswith("- Style:"):
                    result["persona"]["style"] = line[8:].strip()

        # Behavioral Constraints section -> constraints list
        elif header_lower in ("behavioral constraints", "constraints"):
            for line in body.split("\n"):
                line = line.strip()
                if line.startswith("- "):
                    constraint = line[2:].strip()
                    # Skip the standard constraints we add during export
                    if constraint and not constraint.startswith("Respond only with claims") \
                            and not constraint.startswith("If a claim cannot be grounded") \
                            and not constraint.startswith("Tone:"):
                        result["persona"]["constraints"].append(constraint)

        # Knowledge Base / Knowledge section -> kb_sections
        elif header_lower in ("knowledge base", "knowledge"):
            if body:
                result["kb_sections"].append(body)

        # Tech Stack, Gotchas, Patterns -> kb_sections
        elif header_lower in ("tech stack", "coding patterns", "gotchas", "gotchas & memory", "patterns"):
            if body:
                result["kb_sections"].append(f"## {header}\n{body}")

        # Key Concepts -> KG nodes
        elif header_lower in ("key concepts", "concepts"):
            for line in body.split("\n"):
                line = line.strip()
                if line.startswith("- "):
                    # Parse "- Label: Description" format
                    item = line[2:].strip()
                    if ":" in item:
                        label, description = item.split(":", 1)
                        label = label.strip()
                        description = description.strip()
                    else:
                        label = item
                        description = ""

                    # Skip parenthetical counts like "(42 total concepts...)"
                    if label.startswith("(") and label.endswith(")"):
                        continue

                    # Clean label for ID: lowercase, spaces to underscores, remove apostrophes
                    clean_label = label.lower().replace(" ", "_").replace("'", "")
                    node = {
                        "@id": f"aether:concept_{clean_label}",
                        "rdfs:label": label,
                        "aether:description": description,
                        "aether:origin": "core",
                    }
                    result["kg_nodes"].append(node)

        # Anything else -> kb_sections (preserve header + body)
        else:
            if body:
                result["kb_sections"].append(f"## {header}\n{body}")

    return result


def _write_json(path: Path, data: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def stamp_empty(name: str, path: str | Path, version: str = "1.0.0", psi: bool = False) -> Path:
    """Create a new empty capsule folder with all 5 required files (+ optional PSI files)."""
    path = Path(path)
    capsule_id = generate_id(name, version)
    capsule_path = path / capsule_id
    capsule_path.mkdir(parents=True, exist_ok=True)

    # Files are prefixed with folder name: {folder-name}-{type}.{ext}
    prefix = capsule_id
    _write_json(capsule_path / f"{prefix}-manifest.json", {
        "id": capsule_id, "name": name, "version": version, "created": datetime.now().isoformat()
    })
    _write_json(capsule_path / f"{prefix}-definition.json", DEFAULT_DEFINITION)
    _write_json(capsule_path / f"{prefix}-persona.json", DEFAULT_PERSONA)
    (capsule_path / f"{prefix}-kb.md").write_text(DEFAULT_KB, encoding="utf-8")
    _write_json(capsule_path / f"{prefix}-kg.jsonld", DEFAULT_KG)

    # Optional PSI files (6th file + pulse-map)
    if psi:
        psi_data = DEFAULT_PSI.copy()
        psi_data["psi:capsule"] = capsule_id
        _write_json(capsule_path / f"{prefix}-psi.jsonld", psi_data)

        # Copy default pulse-map to capsule
        ui_dir = Path(__file__).parent / "ui"
        default_pulse_map = ui_dir / "pulse-map.default.json"
        if default_pulse_map.exists():
            shutil.copy(default_pulse_map, capsule_path / "pulse-map.json")
        else:
            # Fallback: write inline default
            _write_json(capsule_path / "pulse-map.json", {
                "_comment": "AETHER pulse map. Override per design system.",
                "_version": "1.0.0",
                "discovery": {"--kinetic-tempo": "400ms", "--surface-accent": "#2196F3"},
                "deliberation": {"--kinetic-tempo": "200ms", "--surface-accent": "#FF9800"},
                "validation": {"--kinetic-tempo": "100ms", "--surface-accent": "#9C27B0"},
                "delivery": {"--kinetic-tempo": "0ms", "--surface-accent": "#4CAF50"},
                "ghost": {"--kinetic-tempo": "600ms", "--surface-accent": "#9E9E9E"},
                "recovering": {"--kinetic-tempo": "300ms", "--surface-accent": "#2196F3"}
            })

    return capsule_path


def stamp_from_source(name: str, source_path: str | Path, output_path: str | Path, version: str = "1.0.0", psi: bool = False) -> Path:
    """Create capsule from source file. .md→kb, .jsonld→kg, .json→kg or definition."""
    source_path, output_path = Path(source_path), Path(output_path)
    if not source_path.exists():
        raise FileNotFoundError(f"Source not found: {source_path}")

    capsule_path = stamp_empty(name, output_path, version, psi=psi)
    prefix = capsule_path.name  # Folder name is the prefix
    suffix = source_path.suffix.lower()
    content = source_path.read_text(encoding="utf-8")

    # Detect CLAUDE.md by filename OR AETHER export marker in content
    is_claude_md = (
        source_path.name.upper() == "CLAUDE.MD"
        or (content.startswith("# ") and "Generated by AETHER Export" in content)
    )

    if is_claude_md:
        # Parse CLAUDE.md and populate capsule files
        parsed = _parse_claude_md(content)

        # Write persona.json - merge with defaults
        persona = {**DEFAULT_PERSONA, **parsed["persona"]}
        _write_json(capsule_path / f"{prefix}-persona.json", persona)

        # Write kb.md from kb_sections joined with dividers
        if parsed["kb_sections"]:
            kb_content = "\n\n---\n\n".join(parsed["kb_sections"])
        else:
            kb_content = DEFAULT_KB
        (capsule_path / f"{prefix}-kb.md").write_text(kb_content, encoding="utf-8")

        # Write kg.jsonld if kg_nodes found
        if parsed["kg_nodes"]:
            kg = DEFAULT_KG.copy()
            kg["@graph"] = parsed["kg_nodes"]
            _write_json(capsule_path / f"{prefix}-kg.jsonld", kg)

    elif suffix == ".md":
        (capsule_path / f"{prefix}-kb.md").write_text(content, encoding="utf-8")
    elif suffix == ".jsonld":
        _write_json(capsule_path / f"{prefix}-kg.jsonld", json.loads(content))
    elif suffix == ".json":
        data = json.loads(content)
        if "@graph" in data or "@context" in data or "@id" in data:
            _write_json(capsule_path / f"{prefix}-kg.jsonld", data)
        else:
            _write_json(capsule_path / f"{prefix}-definition.json", {**DEFAULT_DEFINITION, **data})

    return capsule_path


def validate_capsule(path: str | Path) -> dict:
    """Check folder has all required files and they parse correctly."""
    path = Path(path)
    result = {"valid": True, "missing": [], "errors": []}

    if not path.is_dir():
        return {"valid": False, "missing": [f"<folder>{s}" for s in REQUIRED_SUFFIXES.values()], "errors": ["Not a directory"]}

    required_files = get_required_files(path.name)

    for key, filename in required_files.items():
        filepath = path / filename
        if not filepath.exists():
            result["missing"].append(filename)
            result["valid"] = False
            continue

        try:
            content = filepath.read_text(encoding="utf-8")
            if filename.endswith((".json", ".jsonld")):
                data = json.loads(content)
                if key == "manifest":
                    for field in ["id", "version"]:
                        if field not in data:
                            result["errors"].append(f"{filename} missing '{field}'")
                            result["valid"] = False
        except json.JSONDecodeError as e:
            result["errors"].append(f"{filename}: Invalid JSON - {e}")
            result["valid"] = False

    return result


def restamp(path: str | Path, new_version: str) -> Path:
    """Copy existing capsule to new folder with new version, renaming files."""
    path = Path(path)
    validation = validate_capsule(path)
    if not validation["valid"]:
        raise ValueError(f"Invalid source: {validation}")

    old_prefix = path.name
    old_files = get_required_files(old_prefix)
    manifest = json.loads((path / old_files["manifest"]).read_text(encoding="utf-8"))
    name = manifest.get("name", manifest["id"])
    new_id = generate_id(name, new_version)
    new_path = path.parent / new_id
    new_path.mkdir(parents=True, exist_ok=True)

    # Copy and rename files to new prefix
    for key, old_filename in old_files.items():
        old_filepath = path / old_filename
        new_filename = f"{new_id}{REQUIRED_SUFFIXES[key]}"
        new_filepath = new_path / new_filename

        if key == "kb":
            new_filepath.write_text(old_filepath.read_text(encoding="utf-8"), encoding="utf-8")
        else:
            data = json.loads(old_filepath.read_text(encoding="utf-8"))
            if key == "manifest":
                data = {**data, "id": new_id, "version": new_version,
                        "previous_version": manifest["version"], "previous_id": manifest["id"],
                        "restamped": datetime.now().isoformat()}
            _write_json(new_filepath, data)

    # Copy optional sidecar files if present (e.g., engram.jsonld)
    for optional_file in OPTIONAL_CAPSULE_FILES:
        optional_path = path / optional_file
        if optional_path.exists():
            shutil.copy(optional_path, new_path / optional_file)

    return new_path


def export_capsule(capsule_path: str | Path, format: str, output_path: str | Path = None) -> Path:
    """
    Export capsule to target platform format.

    Formats:
    - claude-md: CLAUDE.md workspace brain file
    - claude-skill: .claude/skills/{slug}/SKILL.md
    - github-agent-md: agent.md for GitHub Copilot
    - a2a-agent-card: .well-known/agent-card.json

    Returns the Path of the primary file written.
    Raises ValueError for unknown format or invalid capsule.
    """
    from aether import Capsule, get_required_files

    capsule_path = Path(capsule_path)

    # Validate capsule first
    validation = validate_capsule(capsule_path)
    if not validation["valid"]:
        raise ValueError(f"Invalid capsule: {validation}")

    # Load capsule data
    capsule = Capsule(capsule_path)

    # Valid formats
    valid_formats = ["claude-md", "claude-skill", "github-agent-md", "a2a-agent-card"]
    if format not in valid_formats:
        raise ValueError(f"Unknown format: {format}. Valid formats: {valid_formats}")

    # Helper: extract first sentence from KB
    def get_first_sentence(kb_text: str, capsule_name: str) -> str:
        kb_stripped = kb_text.strip()
        if not kb_stripped or "." not in kb_stripped:
            return f"{capsule_name} knowledge capsule."
        # Skip header lines for first sentence
        lines = [l for l in kb_stripped.split("\n") if l.strip() and not l.strip().startswith("#")]
        if not lines:
            return f"{capsule_name} knowledge capsule."
        first_para = lines[0]
        return first_para.split(".")[0] + "."

    # Helper: get node label
    def get_node_label(node: dict) -> str:
        return node.get("rdfs:label", node.get("@id", "unnamed"))

    # Helper: get node description
    def get_node_description(node: dict) -> str:
        # Try aether:description first
        if "aether:description" in node:
            return node["aether:description"]
        # Try first predicate value that isn't @id, @type, or rdfs:label
        for k, v in node.items():
            if k in ("@id", "@type", "rdfs:label"):
                continue
            if isinstance(v, str):
                return v
            if isinstance(v, (int, float)):
                return str(v)
        return ""

    # Helper: check if KB is default placeholder
    def is_empty_kb(kb_text: str) -> bool:
        return "<!-- Add knowledge content here -->" in kb_text

    # Get capsule data
    kb = capsule.files["kb"]
    kg = capsule.files["kg"]
    persona = capsule.files["persona"]
    kg_nodes = kg.get("@graph", [])

    first_sentence = get_first_sentence(kb, capsule.name)

    # -------------------------------------------------------------------------
    # Format: claude-md
    # -------------------------------------------------------------------------
    if format == "claude-md":
        # Determine output path
        if output_path is None:
            out_file = capsule_path.parent / "CLAUDE.md"
        else:
            output_path = Path(output_path)
            if output_path.suffix == ".md":
                out_file = output_path
            else:
                output_path.mkdir(parents=True, exist_ok=True)
                out_file = output_path / "CLAUDE.md"

        # Build content
        lines = [
            f"# {capsule.name}",
            f"> Generated by AETHER Export | Capsule: {capsule.id} | Version: {capsule.version}",
            "",
            "## Identity",
        ]

        # Persona fields
        lines.append(f"- Tone: {persona.get('tone', 'neutral')}")
        lines.append(f"- Style: {persona.get('style', 'informative')}")
        for constraint in persona.get("constraints", []):
            lines.append(f"- {constraint}")

        lines.append("")
        lines.append("## Knowledge Base")
        lines.append(kb)

        # Key Concepts from KG
        lines.append("")
        lines.append("## Key Concepts")
        if kg_nodes:
            for i, node in enumerate(kg_nodes[:20]):
                label = get_node_label(node)
                desc = get_node_description(node)
                if desc:
                    lines.append(f"- {label}: {desc}")
                else:
                    lines.append(f"- {label}")
            if len(kg_nodes) > 20:
                lines.append(f"({len(kg_nodes)} total concepts in capsule KG)")
        else:
            lines.append("(No concepts in KG — populate kg.jsonld to enable concept grounding.)")

        lines.append("")
        lines.append("## Behavioral Constraints")
        lines.append("- Respond only with claims supported by the Knowledge Base above.")
        lines.append("- If a claim cannot be grounded in the Knowledge Base, state that explicitly.")
        lines.append(f"- Tone: {persona.get('tone', 'neutral')} | Style: {persona.get('style', 'informative')}")
        for constraint in persona.get("constraints", []):
            lines.append(f"- {constraint}")

        # Empty KB warning
        if is_empty_kb(kb):
            lines.append("")
            lines.append("<!-- WARNING: Knowledge Base is empty. Populate kb.md before using this export. -->")

        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text("\n".join(lines), encoding="utf-8")
        return out_file

    # -------------------------------------------------------------------------
    # Format: claude-skill
    # -------------------------------------------------------------------------
    elif format == "claude-skill":
        # Generate slug
        slug = capsule.name.lower().replace(" ", "-")

        # Determine output path
        if output_path is None:
            skill_dir = Path.cwd() / ".claude" / "skills" / slug
        else:
            output_path = Path(output_path)
            skill_dir = output_path / ".claude" / "skills" / slug

        skill_dir.mkdir(parents=True, exist_ok=True)
        out_file = skill_dir / "SKILL.md"

        # Build SKILL.md content
        lines = [
            "---",
            f"name: {slug}",
            f"description: {capsule.name} — AETHER capsule v{capsule.version}. {first_sentence}",
            "---",
            f"# Skill: {capsule.name}",
            "",
            "## Identity",
            f"Tone: {persona.get('tone', 'neutral')} | Style: {persona.get('style', 'informative')}",
            "",
            "## Instructions",
            f"You are {capsule.name}. Answer using only knowledge from the section below.",
            "If a claim is not supported by this knowledge, say so explicitly.",
            "",
            "## Knowledge",
        ]

        # Truncate KB at 4000 chars
        if len(kb) > 4000:
            lines.append(kb[:4000])
            lines.append(f"\n\n... [truncated — {len(kb)} chars total. Full knowledge available in capsule kb.md]")
        else:
            lines.append(kb)

        # Key Concepts (cap at 15)
        lines.append("")
        lines.append("## Key Concepts")
        if kg_nodes:
            for i, node in enumerate(kg_nodes[:15]):
                label = get_node_label(node)
                desc = get_node_description(node)
                if desc:
                    lines.append(f"- {label}: {desc}")
                else:
                    lines.append(f"- {label}")
            if len(kg_nodes) > 15:
                lines.append(f"({len(kg_nodes)} total concepts in capsule KG)")
        else:
            lines.append("(No concepts in KG — populate kg.jsonld to enable concept grounding.)")

        # Empty KB warning
        if is_empty_kb(kb):
            lines.append("")
            lines.append("<!-- WARNING: Knowledge Base is empty. Populate kb.md before using this export. -->")

        out_file.write_text("\n".join(lines), encoding="utf-8")
        return out_file

    # -------------------------------------------------------------------------
    # Format: github-agent-md
    # -------------------------------------------------------------------------
    elif format == "github-agent-md":
        # Determine output path
        if output_path is None:
            out_file = capsule_path.parent / "agent.md"
        else:
            output_path = Path(output_path)
            if output_path.suffix == ".md":
                out_file = output_path
            else:
                output_path.mkdir(parents=True, exist_ok=True)
                out_file = output_path / "agent.md"

        # Build content
        lines = [
            "---",
            f"name: {capsule.name}",
            f"description: {first_sentence}",
            f"version: {capsule.version}",
            "---",
            "",
            f"# {capsule.name}",
            "",
            "## Persona",
            f"- Tone: {persona.get('tone', 'neutral')}",
            f"- Style: {persona.get('style', 'informative')}",
        ]
        for constraint in persona.get("constraints", []):
            lines.append(f"- {constraint}")

        lines.append("")
        lines.append("## Knowledge Base")
        lines.append(kb)

        lines.append("")
        lines.append("## Constraints")
        lines.append("- Ground all responses in the Knowledge Base above.")
        lines.append("- Do not make claims unsupported by the Knowledge Base.")
        lines.append("- If asked about topics outside this knowledge base, acknowledge the limitation.")

        # Empty KB warning
        if is_empty_kb(kb):
            lines.append("")
            lines.append("<!-- WARNING: Knowledge Base is empty. Populate kb.md before using this export. -->")

        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text("\n".join(lines), encoding="utf-8")
        return out_file

    # -------------------------------------------------------------------------
    # Format: a2a-agent-card
    # -------------------------------------------------------------------------
    elif format == "a2a-agent-card":
        # Determine output path
        if output_path is None:
            well_known_dir = capsule_path.parent / ".well-known"
        else:
            output_path = Path(output_path)
            well_known_dir = output_path / ".well-known"

        well_known_dir.mkdir(parents=True, exist_ok=True)
        out_file = well_known_dir / "agent-card.json"

        # Build JSON
        node_labels = [get_node_label(n) for n in kg_nodes[:10]]

        agent_card = {
            "schemaVersion": "1.0",
            "name": capsule.name,
            "id": capsule.id,
            "version": capsule.version,
            "description": first_sentence,
            "persona": {
                "tone": persona.get("tone", "neutral"),
                "style": persona.get("style", "informative")
            },
            "capabilities": {
                "pipeline": ["distill", "augment", "generate", "review"],
                "aec": True,
                "self_education": True,
                "ghost_state": True
            },
            "knowledge": {
                "kb_chars": len(kb),
                "kg_nodes": len(kg_nodes),
                "kg_node_labels": node_labels
            },
            "aether": {
                "framework": "AETHER",
                "capsule_format": "5-file",
                "exported": datetime.now().isoformat()
            }
        }

        _write_json(out_file, agent_card)
        return out_file


if __name__ == "__main__":
    import tempfile
    import re
    with tempfile.TemporaryDirectory() as tmp:
        # Test stamp_empty
        cap1 = stamp_empty("Jefferson Agent", tmp)
        print(f"Created: {cap1.name}")

        # Verify format: {slug}-v{version}-{uid8}
        pattern = r"^[a-z0-9-]+-v\d+\.\d+\.\d+-[a-f0-9]{8}$"
        assert re.match(pattern, cap1.name), f"ID format mismatch: {cap1.name}"
        print(f"Format OK: {cap1.name}")

        # Verify files are prefixed with folder name
        files = [f.name for f in cap1.iterdir()]
        print(f"Files: {files}")
        assert all(f.startswith(cap1.name) for f in files), "Files not prefixed correctly"
        print(f"Valid: {validate_capsule(cap1)['valid']}")

        # Test restamp with lineage
        cap2 = restamp(cap1, "1.1.0")
        files2 = get_required_files(cap2.name)
        m2 = json.loads((cap2 / files2["manifest"]).read_text())

        print(f"\nRestamped: {cap1.name} -> {cap2.name}")
        print(f"Lineage: previous_id={m2.get('previous_id')}, previous_version={m2.get('previous_version')}")
        assert m2["previous_id"] == cap1.name, "Lineage not tracked"
        assert m2["previous_version"] == "1.0.0", "Previous version not tracked"
        assert cap1.name != cap2.name, "UIDs should differ"
        print("All tests passed!")
