/**
 * generate_docx_demo.js - AETHER docx Demo Generator
 *
 * Generates a project status report .docx file following ALL rules from SKILL.md:
 * - US Letter page size (12240 x 15840 DXA)
 * - 1 inch margins (1440 DXA all sides)
 * - Arial font, size 24 (12pt) default
 * - Heading 1 override: Arial, bold, size 32, outlineLevel 0
 * - Heading 2 override: Arial, bold, size 28, outlineLevel 1
 * - Tables: columnWidths + cell width, both DXA, ShadingType.CLEAR
 * - Footer: "Generated by AETHER docx agent v1.0.0"
 *
 * Usage: node generate_docx_demo.js <output_path>
 *        Reads response text from stdin (optional)
 */

const {
    Document,
    Packer,
    Paragraph,
    TextRun,
    Table,
    TableRow,
    TableCell,
    Header,
    Footer,
    AlignmentType,
    HeadingLevel,
    WidthType,
    ShadingType,
    BorderStyle,
    TableLayoutType,
    convertInchesToTwip,
    PageOrientation,
} = require('docx');

const fs = require('fs');
const path = require('path');

// Page dimensions in DXA (twips) - US Letter
const PAGE_WIDTH = 12240;  // 8.5 inches
const PAGE_HEIGHT = 15840; // 11 inches
const MARGIN = 1440;       // 1 inch

// Colors
const HEADER_BG = "2E4057";  // Dark blue
const ALT_ROW_BG = "F5F5F5"; // Light gray

// Calculate usable width for tables
const TABLE_WIDTH = PAGE_WIDTH - (2 * MARGIN); // 9360 DXA

async function generateDocx(outputPath) {
    const doc = new Document({
        styles: {
            default: {
                document: {
                    run: {
                        font: "Arial",
                        size: 24, // 12pt
                    },
                },
            },
            paragraphStyles: [
                {
                    id: "Heading1",
                    name: "Heading 1",
                    basedOn: "Normal",
                    next: "Normal",
                    quickFormat: true,
                    run: {
                        font: "Arial",
                        size: 32, // 16pt
                        bold: true,
                        color: "000000",
                    },
                    paragraph: {
                        spacing: { before: 480, after: 240 },
                        outlineLevel: 0,
                    },
                },
                {
                    id: "Heading2",
                    name: "Heading 2",
                    basedOn: "Normal",
                    next: "Normal",
                    quickFormat: true,
                    run: {
                        font: "Arial",
                        size: 28, // 14pt
                        bold: true,
                        color: "000000",
                    },
                    paragraph: {
                        spacing: { before: 360, after: 180 },
                        outlineLevel: 1,
                    },
                },
                {
                    id: "Title",
                    name: "Title",
                    basedOn: "Normal",
                    next: "Normal",
                    run: {
                        font: "Arial",
                        size: 48, // 24pt
                        bold: true,
                        color: "000000",
                    },
                    paragraph: {
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 400 },
                    },
                },
            ],
        },
        sections: [{
            properties: {
                page: {
                    size: {
                        width: PAGE_WIDTH,
                        height: PAGE_HEIGHT,
                        orientation: PageOrientation.PORTRAIT,
                    },
                    margin: {
                        top: MARGIN,
                        right: MARGIN,
                        bottom: MARGIN,
                        left: MARGIN,
                    },
                },
            },
            footers: {
                default: new Footer({
                    children: [
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: "Generated by AETHER docx agent v1.0.0",
                                    font: "Arial",
                                    size: 20, // 10pt
                                    italics: true,
                                    color: "666666",
                                }),
                            ],
                            alignment: AlignmentType.CENTER,
                        }),
                    ],
                }),
            },
            children: [
                // Title
                new Paragraph({
                    text: "Project Status Report",
                    style: "Title",
                }),

                // Executive Summary Section
                new Paragraph({
                    text: "Executive Summary",
                    heading: HeadingLevel.HEADING_1,
                }),
                new Paragraph({
                    children: [
                        new TextRun({
                            text: "This report provides a comprehensive overview of the current project status, including key milestones, deliverables, and risk assessment. The project is progressing according to plan with Phase 1 complete and Phase 2 currently in progress.",
                            font: "Arial",
                            size: 24,
                        }),
                    ],
                    spacing: { after: 200 },
                }),
                new Paragraph({
                    children: [
                        new TextRun({
                            text: "Key highlights include successful completion of initial deliverables, identification of potential risks with mitigation strategies in place, and alignment with stakeholder expectations for the upcoming milestones.",
                            font: "Arial",
                            size: 24,
                        }),
                    ],
                    spacing: { after: 400 },
                }),

                // Milestones Section
                new Paragraph({
                    text: "Milestones",
                    heading: HeadingLevel.HEADING_1,
                }),
                createMilestonesTable(),

                // Risk Register Section
                new Paragraph({
                    text: "Risk Register",
                    heading: HeadingLevel.HEADING_1,
                    spacing: { before: 400 },
                }),
                createRiskTable(),
            ],
        }],
    });

    // Generate the document
    const buffer = await Packer.toBuffer(doc);

    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    if (outputDir && !fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, buffer);

    const stats = fs.statSync(outputPath);
    console.log(JSON.stringify({
        success: true,
        path: outputPath,
        size_bytes: stats.size,
        size_kb: Math.round(stats.size / 1024),
    }));
}

function createTableCell(text, isHeader = false, width = null, altRow = false) {
    const cellOptions = {
        children: [
            new Paragraph({
                children: [
                    new TextRun({
                        text: text,
                        font: "Arial",
                        size: 22, // 11pt
                        bold: isHeader,
                        color: isHeader ? "FFFFFF" : "000000",
                    }),
                ],
            }),
        ],
        // CRITICAL: Use ShadingType.CLEAR (not SOLID) per SKILL.md
        shading: {
            type: ShadingType.CLEAR,
            fill: isHeader ? HEADER_BG : (altRow ? ALT_ROW_BG : "FFFFFF"),
        },
    };

    // CRITICAL: Set width on EACH cell (dual width rule)
    if (width) {
        cellOptions.width = {
            size: width,
            type: WidthType.DXA,
        };
    }

    return new TableCell(cellOptions);
}

function createMilestonesTable() {
    // 3 equal columns: 3120 DXA each (9360 / 3)
    const colWidth = 3120;

    const milestones = [
        ["Milestone", "Target Date", "Status"],
        ["Phase 1 Complete", "2026-Q1", "Complete"],
        ["Phase 2 Kickoff", "2026-Q2", "In Progress"],
        ["Final Delivery", "2026-Q4", "Planned"],
    ];

    const rows = milestones.map((row, rowIndex) => {
        const isHeader = rowIndex === 0;
        const isAltRow = !isHeader && rowIndex % 2 === 0;

        return new TableRow({
            children: row.map(cell =>
                createTableCell(cell, isHeader, colWidth, isAltRow)
            ),
        });
    });

    return new Table({
        // CRITICAL: Set columnWidths on table (dual width rule)
        columnWidths: [colWidth, colWidth, colWidth],
        width: {
            size: TABLE_WIDTH,
            type: WidthType.DXA,
        },
        layout: TableLayoutType.FIXED,
        rows: rows,
    });
}

function createRiskTable() {
    // 4 equal columns: 2340 DXA each (9360 / 4)
    const colWidth = 2340;

    const risks = [
        ["Risk", "Impact", "Probability", "Mitigation"],
        ["Resource constraints", "High", "Medium", "Cross-train team members"],
        ["Scope creep", "Medium", "High", "Strict change control process"],
    ];

    const rows = risks.map((row, rowIndex) => {
        const isHeader = rowIndex === 0;
        const isAltRow = !isHeader && rowIndex % 2 === 0;

        return new TableRow({
            children: row.map(cell =>
                createTableCell(cell, isHeader, colWidth, isAltRow)
            ),
        });
    });

    return new Table({
        columnWidths: [colWidth, colWidth, colWidth, colWidth],
        width: {
            size: TABLE_WIDTH,
            type: WidthType.DXA,
        },
        layout: TableLayoutType.FIXED,
        rows: rows,
    });
}

// Main execution
const outputPath = process.argv[2] || 'outputs/docx-demo-output.docx';

generateDocx(outputPath).catch(err => {
    console.error(JSON.stringify({
        success: false,
        error: err.message,
    }));
    process.exit(1);
});
